import { Category, Level, Trick, ShopItem } from './types';

export const TRICKS_DATA: Trick[] = [
  // LEVEL A
  { id: 'a1', name: 'Butterfly Cross', level: Level.A, category: Category.OTHERS },
  { id: 'a2', name: 'Back Toe Christie', level: Level.A, category: Category.SITTING },
  { id: 'a3', name: 'Toe Christie', level: Level.A, category: Category.SITTING },
  { id: 'a4', name: 'Toe Wiper', level: Level.A, category: Category.SITTING },
  { id: 'a5', name: 'Front Toe Footgun Kazachok', level: Level.A, category: Category.JUMPING },
  { id: 'a6', name: 'Heel Wiper', level: Level.A, category: Category.JUMPING },
  { id: 'a7', name: 'Backward Leaf Series', level: Level.A, category: Category.WHEELING },
  { id: 'a8', name: 'Side/forward Leaf Series', level: Level.A, category: Category.WHEELING },
  { id: 'a9', name: 'Wheeling Shifts / CounterShifts Series', level: Level.A, category: Category.WHEELING },
  { id: 'a10', name: 'Square Series', level: Level.A, category: Category.WHEELING },
  { id: 'a11', name: 'Back Toe Christie Spin', level: Level.A, category: Category.SPINNING },
  { id: 'a12', name: 'Toe Christie Spin', level: Level.A, category: Category.SPINNING },
  { id: 'a13', name: 'Back Toe Footgun Spin', level: Level.A, category: Category.SPINNING },
  { id: 'a14', name: 'Toe Footgun spin', level: Level.A, category: Category.SPINNING },
  { id: 'a15', name: 'Back Seven int/ext', level: Level.A, category: Category.SPINNING },
  { id: 'a16', name: '1 Cone Toe Footgun Spin', level: Level.A, category: Category.SPINNING },
  
  // LEVEL B
  { id: 'b1', name: 'Butterfly', level: Level.B, category: Category.OTHERS },
  { id: 'b2', name: 'Toe Toe Reveres Eagle', level: Level.B, category: Category.OTHERS },
  { id: 'b3', name: 'Back Teapot / Back Superman', level: Level.B, category: Category.SITTING },
  { id: 'b4', name: 'Back Toe Footgun', level: Level.B, category: Category.SITTING },
  { id: 'b5', name: 'Tea pot / Superman', level: Level.B, category: Category.SITTING },
  { id: 'b6', name: 'Toe Footgun', level: Level.B, category: Category.SITTING },
  { id: 'b7', name: 'Footgun Spin Jump', level: Level.B, category: Category.JUMPING },
  { id: 'b8', name: 'Footgun Wiper', level: Level.B, category: Category.JUMPING },
  { id: 'b9', name: 'Back Kazachok', level: Level.B, category: Category.JUMPING },
  { id: 'b10', name: 'Wheeling Flip / DayNight Series', level: Level.B, category: Category.WHEELING },
  { id: 'b11', name: 'French Shift Series', level: Level.B, category: Category.WHEELING },
  { id: 'b12', name: 'Toe Swing Machine', level: Level.B, category: Category.WHEELING },
  { id: 'b13', name: 'Seven (in/ext)', level: Level.B, category: Category.SPINNING },
  { id: 'b14', name: 'One Cone Seven int/ext', level: Level.B, category: Category.SPINNING },
  { id: 'b15', name: 'Flat Back Seven (int/ext)', level: Level.B, category: Category.SPINNING },
  { id: 'b16', name: 'Flat Seven int/ext', level: Level.B, category: Category.SPINNING },
  { id: 'b17', name: 'One Cone Back Korean Spin', level: Level.B, category: Category.SPINNING },

  // LEVEL C
  { id: 'c1', name: 'Back Cobra', level: Level.C, category: Category.OTHERS },
  { id: 'c2', name: 'Cobra', level: Level.C, category: Category.OTHERS },
  { id: 'c3', name: 'Reverse Eagle', level: Level.C, category: Category.OTHERS },
  { id: 'c4', name: 'Two Wheels Eagle', level: Level.C, category: Category.OTHERS },
  { id: 'c5', name: 'Z-Eagle', level: Level.C, category: Category.OTHERS },
  { id: 'c6', name: 'Back Sitting Cobra', level: Level.C, category: Category.SITTING },
  { id: 'c7', name: 'Back Christie', level: Level.C, category: Category.SITTING },
  { id: 'c8', name: 'Sitting Cobra', level: Level.C, category: Category.SITTING },
  { id: 'c9', name: 'Back Footgun', level: Level.C, category: Category.SITTING },
  { id: 'c10', name: 'Footgun', level: Level.C, category: Category.SITTING },
  { id: 'c11', name: 'Kazachok', level: Level.C, category: Category.JUMPING },
  { id: 'c12', name: 'Kazachok Spin', level: Level.C, category: Category.JUMPING },
  { id: 'c13', name: 'Front Wiper', level: Level.C, category: Category.JUMPING },
  { id: 'c14', name: 'Wiper', level: Level.C, category: Category.JUMPING },
  { id: 'c15', name: 'Back Wheeling', level: Level.C, category: Category.WHEELING },
  { id: 'c16', name: 'Flat Shifts / Countershifts Series', level: Level.C, category: Category.WHEELING },
  { id: 'c17', name: 'FWD Wheeling', level: Level.C, category: Category.WHEELING },
  { id: 'c18', name: 'Flat Flip / Daynight Series', level: Level.C, category: Category.WHEELING },
  { id: 'c19', name: 'Back Korean Spin', level: Level.C, category: Category.SPINNING },
  { id: 'c20', name: 'One Cone Korean Spin', level: Level.C, category: Category.SPINNING },
  { id: 'c21', name: 'Back Two Wheel Spin', level: Level.C, category: Category.SPINNING },
  { id: 'c22', name: 'Two Wheels Spin', level: Level.C, category: Category.SPINNING },
  { id: 'c23', name: 'Back J-Turn', level: Level.C, category: Category.SPINNING },

  // LEVEL D
  { id: 'd1', name: 'Toe Toe Special', level: Level.D, category: Category.OTHERS },
  { id: 'd2', name: 'Brush', level: Level.D, category: Category.OTHERS },
  { id: 'd3', name: 'Eagle / Eagle Cross', level: Level.D, category: Category.OTHERS },
  { id: 'd4', name: 'Sweepers', level: Level.D, category: Category.OTHERS },
  { id: 'd5', name: 'Heel Toe Special', level: Level.D, category: Category.OTHERS },
  { id: 'd6', name: 'Sitting Heel Toe Back Cross', level: Level.D, category: Category.SITTING },
  { id: 'd7', name: 'Sitting Heel Toe Cross', level: Level.D, category: Category.SITTING },
  { id: 'd8', name: 'Back Sitting Heel Toe Snake', level: Level.D, category: Category.SITTING },
  { id: 'd9', name: 'Sitting Heel Toe Snake', level: Level.D, category: Category.SITTING },
  { id: 'd10', name: 'Footspin Jump', level: Level.D, category: Category.JUMPING },
  { id: 'd11', name: 'Two Wheels Snake', level: Level.D, category: Category.WHEELING },
  { id: 'd12', name: 'Two Wheels Back Cross', level: Level.D, category: Category.WHEELING },
  { id: 'd13', name: 'Two Wheels Back Snake', level: Level.D, category: Category.WHEELING },
  { id: 'd14', name: 'Two Wheels Cross', level: Level.D, category: Category.WHEELING },
  { id: 'd15', name: 'J-Turn', level: Level.D, category: Category.SPINNING },
  { id: 'd16', name: 'Two Feet Spin', level: Level.D, category: Category.SPINNING },
  { id: 'd17', name: 'Total Cross', level: Level.D, category: Category.SPINNING },

  // LEVEL E
  { id: 'e1', name: 'Eight', level: Level.E, category: Category.OTHERS },
  { id: 'e2', name: 'Back Eight', level: Level.E, category: Category.OTHERS },
  { id: 'e3', name: 'Stroll / Back Stroll', level: Level.E, category: Category.OTHERS },
  { id: 'e4', name: 'Crazy / Double Crazy Series', level: Level.E, category: Category.OTHERS },
  { id: 'e5', name: 'ChapChap / x', level: Level.E, category: Category.OTHERS },
  { id: 'e6', name: 'Mega Series', level: Level.E, category: Category.OTHERS },
  { id: 'e7', name: 'Nelson / Back Nelson Series', level: Level.E, category: Category.OTHERS },
  { id: 'e8', name: 'Small Cart / 5 Wheels Sitting', level: Level.E, category: Category.SITTING },
  { id: 'e9', name: 'Sitting Fish', level: Level.E, category: Category.SITTING },
  { id: 'e10', name: 'X Jump', level: Level.E, category: Category.JUMPING },
  { id: 'e11', name: 'Crab Cross', level: Level.E, category: Category.JUMPING },
  { id: 'e12', name: 'Crab Series', level: Level.E, category: Category.JUMPING },
  { id: 'e13', name: 'Back One Foot', level: Level.E, category: Category.WHEELING },
  { id: 'e14', name: 'One Foot', level: Level.E, category: Category.WHEELING },
  { id: 'e15', name: 'Back Snake / Back Cross', level: Level.E, category: Category.WHEELING },
  { id: 'e16', name: 'Snake / Cross', level: Level.E, category: Category.WHEELING },
  { id: 'e17', name: 'Fish', level: Level.E, category: Category.WHEELING },
  { id: 'e18', name: 'Italian / Volt', level: Level.E, category: Category.SPINNING },
  { id: 'e19', name: 'Crazy Sun / Mexican', level: Level.E, category: Category.SPINNING },
  { id: 'e20', name: 'Sun / Mabrouk', level: Level.E, category: Category.SPINNING },
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 's1', name: 'چرخ‌های نورانی (Luminous)', description: 'چرخ‌های ال‌ای‌دی دار درخشان برای بتل شبانه (سطح A)', requiredBadgeLevel: Level.A, cost: 500, image: '' },
  { id: 's2', name: 'بلبرینگ‌های سرامیکی', description: 'بلبرینگ‌های سرعتی و روان', requiredBadgeLevel: Level.A, cost: 400, image: '' },
  { id: 's3', name: 'جوراب اسکیت حرفه‌ای', description: 'تقویت شده در پاشنه و پنجه', requiredBadgeLevel: Level.B, cost: 250, image: '' },
  { id: 's4', name: 'فریم راکر (موزی)', description: 'فریم تخصصی برای مانورهای چرخشی', requiredBadgeLevel: Level.B, cost: 600, image: '' },
  { id: 's5', name: 'مانع‌های تمرینی (۲۰ عدد)', description: 'مانع‌های استاندارد دو دانسیته', requiredBadgeLevel: Level.C, cost: 150, image: '' },
  { id: 's6', name: 'کوله پشتی اسکیت', description: 'طراحی مثلثی برای حمل آسان', requiredBadgeLevel: Level.C, cost: 300, image: '' },
  { id: 's7', name: 'بند اسکیت مومی', description: 'محکم و با دوام', requiredBadgeLevel: Level.D, cost: 50, image: '' },
  { id: 's8', name: 'پک استیکر', description: 'برچسب‌های برندهای معروف', requiredBadgeLevel: Level.E, cost: 20, image: '' },
  { id: 's9', name: 'مچ‌بند محافظ', description: 'محافظت پایه برای ایمنی', requiredBadgeLevel: Level.E, cost: 100, image: '' },
];

export const POINTS_PER_LEVEL = {
  [Level.A]: 5,
  [Level.B]: 4,
  [Level.C]: 3,
  [Level.D]: 2,
  [Level.E]: 1,
};